### ISSUE TITLE
Stable Version v0.1.0 discussion board

### ISSUE THREAD

**Issue by hueitan** [hueitan/snap.svg.zpd#14]
@tikiatua Here's we talk about the stable version v0.1.0
which push to commit to branch [beta_v0.1.0](https://github.com/huei90/snap.svg.zpd/tree/beta_v0.1.0)

**Comment by huei90** [comment]
Hi @tikiatua Since the Github Traffic Graph shows that there're still lot of viewing/searching on this project. Do you still have time on developing it?

**Comment by huei90** [comment]
Reference #18

**Comment by huei90** [comment]
nudge @tikiatua Need your reply.

**Comment by tikiatua** [comment]
Hi @huei90,

I am currently very busy on a few other projects but managed to negotiate a few days to spend on the zpd plugin in January. I think we should work on the api interface for version 1.0 first and then implement the functionality accordingly.

It might also be helpful to change the structure of the plugin to work in a more event based way, as this would make it easier to integrate multiple interaction possibilities (i.e. sliders, touch events, device movements). 

I would propose to attach a zpd property to the Paper prototype and implement the functions as subproperties of this zpd element. This would also allow for easier extension of the plugins functionality with additional methods. A drawback would be that it breaks backward compatibility (but this is allowed for major version changes).

```javascript
Paper.prototype.zpd = {
  init: function(){..},
  enable: function(){..},
  disable: function(){..},
  zoomTo: function(){..}
}

// could be used somehow like this
var paper = Snap();
paper.zpd.init();
paper.zpd.zoomTo("4x");
```

In regard to the event system I would still need to look into how Snap.svg handles event internally, but I think it still uses the same system as Raphaeljs http://raphaeljs.com/reference.html#eve. It would probably make sense to harness the functionality already provided.

**Comment by hueitan** [comment]
close as stale discussion, open if there is any plan for the new release / discussion
