### ISSUE TITLE
new feature: limit pan directions

### ISSUE THREAD

**Issue by erazor83** [hueitan/snap.svg.zpd#69]
I'm wondering how to name new functions or settings to limit directions of panning.

For example I'd like to enable horizontal or vertical panning only.

Any suggestions?

**Comment by huei90** [comment]
Nice suggestion, but unfortunately `snap.svg.zpd` doesn't have this feature now.

**Comment by erazor83** [comment]
i know... i would add it

first of all, i probably have to add a new property which can be changed, like pan_directions="both"|"vertical"|"horizontal"

**Comment by erazor83** [comment]
Got something working already:

I'd start like this:
[code]
        var snapsvgzpd = {
            uniqueIdPrefix: 'snapsvg-zpd-',     // prefix for the unique ids created for zpd
            dataStore: {},                      // "global" storage for all our zpd elements
            enable: true,                       // By default, snapsvgzpd should enable, zpd('toggle') to toggle enable or disable
            panDirections: 'both'               // set pan directions: "both" | "horizontal" | "vertical"
        };
[/code]

**Comment by MarkCarrier** [comment]
`panDirections: 'horizontal'` made my day! Thank you. The README should be updated to advertise this great feature.  

Pull request created: https://github.com/hueitan/snap.svg.zpd/pull/84
